apiVersion: v2
name: traccar
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "4.13"
dependencies:
  - name: mysql
    version: 8.6.2
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
