apiVersion: v1
kind: Service
metadata:
  name: {{ include "traccar.fullname" . }}
  labels:
    {{- include "traccar.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- toYaml .Values.service.protocolPorts | nindent 4 }}
  selector:
    {{- include "traccar.selectorLabels" . | nindent 4 }}
